### ISSUE TITLE
question about generate corrupution data

### ISSUE THREAD

**Issue by MaybeOjbk** [EPFL-VILAB/3DCommonCorruptions#1]
I want to generate different light condition image, but follow your instructions, I need BASE_PATH_RELIGHTING, how can I generate Relighting data use blender?  Do I need follow Omnidata to generate relight image?

**Comment by ofkar** [comment]
Hi, the script to generate relighting data is provided [here](https://github.com/EPFL-VILAB/3DCommonCorruptions/tree/main/create_3dcc/lighting). See [this](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/main/create_3dcc/lighting/create_albedo_images.py#L1-L5) for instructions. 

Best
Oguzhan

**Comment by ofkar** [comment]
Hi, the script to generate relighting data is provided [here](https://github.com/EPFL-VILAB/3DCommonCorruptions/tree/main/create_3dcc/lighting). See [this](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/main/create_3dcc/lighting/create_albedo_images.py#L1-L5) for instructions. 

Best
Oguzhan

**Comment by MaybeOjbk** [comment]
ok， thanks
