### ISSUE TITLE
Very large files in the val set

### ISSUE THREAD

**Issue by max-andr** [EPFL-VILAB/3DCommonCorruptions#5]
Hey!

I'm downloading your validation set via [this script](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/main/tools/download_imagenet_3dcc.sh). I'm curious, why are these files so big, i.e., around 90 GB each?
[imagenet_3dcc/bit_error.tar.gz](https://datasets.epfl.ch/3dcc/imagenet_3dcc/bit_error.tar.gz)
[imagenet_3dcc/h265_abr.tar.gz](https://datasets.epfl.ch/3dcc/imagenet_3dcc/h265_abr.tar.gz)
[imagenet_3dcc/h265_crf.tar.gz](https://datasets.epfl.ch/3dcc/imagenet_3dcc/h265_crf.tar.gz)

At the same time, the rest of the files are on the order of 1-2 GB.

Thanks in advance.

**Comment by ofkar** [comment]
Hi Maksym! Those represent video compression artifacts, i.e the compression wasn’t running properly, hence resulting in larger file sizes. So this is expected.

**Comment by max-andr** [comment]
got it, thanks!
