### ISSUE TITLE
Filter file not found and different data structure

### ISSUE THREAD

**Issue by Twilight89** [EPFL-VILAB/3DCommonCorruptions#6]
Hi, thanks for your wonderful open-source work.

I'm trying to reproduce the train_depth process, and currently, I have two questions:

1. In these [two](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/e3c000c69affb4d3d2e242901885be18b8529ebe/train/data/taskonomy_replica_gso_dataset.py#L48) [line](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/e3c000c69affb4d3d2e242901885be18b8529ebe/train/data/taskonomy_replica_gso_dataset.py#L62), they are supposed to read filter files which I couldn't find in the repo or in the omnidata repo. I also have a look in the omnidata repo, it seems in the omnidata_dataset.py, they are all annotated. 
2. I down load the omnidata following the guide, but unfortunately, I found the dataset structure which is /omnidata/{tasks}/{datasets}/{scenes}, is different from the dataset structure in the dataloader file which is /omnidata/{dataset}/{tasks}/{scenes}. Is this normal and I just need to change the code of dataloader, or I did something wrong when downloading the omnidata?

Hope for your reply, thanks :)

**Comment by roman-bachmann** [comment]
Hi @Twilight89 ,

Thanks for pointing out the missing files! We added them to the repo.

Regarding the dataset structure, the download script uses the dataset/task/scene format by default, but you can easily change this behaviour and make it fit your needs by changing the order [here](https://github.com/EPFL-VILAB/omnidata/blob/main/omnidata_tools/dataset/download.py#L277).

Best, Roman

**Comment by Twilight89** [comment]
@roman-bachmann  appreciate your reply.

Since I have downloaded the data, which cost one week nearly. So what I do is change the dataset and dataloader file. I have another issue below.

Cause I aim at reproducing the v2 pre-trained model. And according below image, the v2 model is stronger than v1 because the 3D augmentation, cross-task consistency and more data in MiDaS.

My Understanding is, the train code in omnidata repo is v1, and this repo based on is and added 3D augmentation. The remaining update (cross-task consistency and more data in MiDaS) code is not open-source, right ? So:

1. Do you have the plan to release all v2 train code? If not, could you give a brief intro on how the three updates (a. 3D aug, b. cross-task, c. more data) increase the depth estimation result?
2. I see v2 pre-trained model was trained one week for aug and one week for cross-task. But when I reproduce v1 model, which is implemented in omnidata repo (which only has omnidata dataset), one epoch training cost 3 days plus (3 V100 gpus), and the default training epoch is 10... So could you tell us how many gpus do you use and how many epochs to be trained?

Thanks, 

<img width="826" alt="image" src="https://user-images.githubusercontent.com/60816348/231635568-5248e5f1-6326-4d74-8c82-3e40e326e1c6.png">
