### ISSUE TITLE
About training code of v2 depth pretrained model

### ISSUE THREAD

**Issue by Twilight89** [EPFL-VILAB/3DCommonCorruptions#7]
Hi, this issue is original propose in [https://github.com/EPFL-VILAB/3DCommonCorruptions/issues/6#issuecomment-1506262636](there)

Cause I aim at reproducing the v2 pre-trained model. And according below image, the v2 model is stronger than v1 because the 3D augmentation, cross-task consistency, and more data in MiDaS.

My Understanding is, the train code in omnidata repo is v1, and this repo based on is and added 3D augmentation. The remaining update (cross-task consistency and more data in MiDaS) code is not open-source, right? So:

Do you have the plan to release all v2 train code? If not, could you give a brief intro on how the three updates (a. 3D aug, b. cross-task, c. more data) increase the depth estimation result?
I see v2 pre-trained model was trained one week for aug and one week for cross-task. But when I reproduce v1 model, which is implemented in omnidata repo (which only has omnidata dataset), one epoch training cost 3 days plus (3 V100 gpus), and the default training epoch is 10... So could you tell us how many gpus do you use and how many epochs are to be trained?

Thanks,

<img width="807" alt="image" src="https://user-images.githubusercontent.com/60816348/231642756-49ead5b4-ac07-49ba-a78a-ebf9a7f0269c.png">

**Comment by ofkar** [comment]
Hi @Twilight89 the v2 models are trained sequentially with Omnidata, Consistency, and the augmentations. We have the ablations of individual components in the paper for surface normals which should give an idea. For training, we used 4xV100s with PyTorch lightning.
